import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/header/Kontakt.module.css'
import Footer from '../components/Footer'

export default function Kontakt() {
  return (
    <div>
      <Head>
        <title>ZIIL-TAXI: Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Header */}
    <Header/>
    <div className={styles.form}>
    <div className={styles.title}>
        <h1>Kontakt</h1>
      </div>
      <div >
        <form className={styles.backForm}>
        <div className={styles.nameMail} >
          <div className={styles.input} >
            <label >Vorname</label>
            <input className={styles.name} type="text" name="name" />
          </div>
          
          <div className={styles.input} >
            <label>Nachname</label>
            <input className={styles.name} type="email" name="email" />
          </div>
          </div>
          <div className={styles.nameMail} >
          <div className={styles.input} >
            <label >Email</label>
            <input className={styles.name} type="text" name="name" />
          </div>
          
          <div className={styles.input} >
            <label>Telefon</label>
            <input className={styles.name} type="email" name="email" />
          </div>
          </div>
          <div className={styles.input} >
            <label>Nachricht</label>
            <textarea className={styles.textArea} placeholdername="message" rows="10" cols="50"></textarea>
          </div>
          <div>
            <button className={styles.button} type="submit">Senden</button>
          </div>
        </form>
      </div>
    </div>

    {/* Banner */}

    
    <Footer/>
    </div>
  )
}